# Generated by Django 2.2.2 on 2019-06-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Date_Of_Birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Othet', 'Other')], max_length=10, null=True),
        ),
    ]
