# Generated by Django 2.2.2 on 2019-06-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190614_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='gender',
            new_name='Gender',
        ),
    ]
