# Generated by Django 2.2.2 on 2019-06-28 08:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190624_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, max_length=500),
        ),
    ]
