# Generated by Django 2.2.2 on 2019-06-28 10:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190628_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
