# Generated by Django 2.2.2 on 2019-06-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dateposted',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='lastupdated',
            new_name='last_updated',
        ),
    ]
