# Generated by Django 2.2.2 on 2019-06-24 09:49

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190615_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(default='nopic.jpg', upload_to=blog.models.Post.post_pic_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='nopic.jpg', max_length=1000),
        ),
    ]
